In [ ]:
2.1. Problem Statement: Machine Learning 7
predict how many points NBA players scored in the 2013-2014
season using k Nearest Neighbours
A look at the data
Before we dive into the algorithm, let’s take a look at our data. Each row in
the data contains information on how a player performed in the 2013-2014
NBA season.
Download 'nba_2013.csv' file from this link:
https://www.dropbox.com/s/b3nv38jjo5dxcl6/nba_2013.csv?dl=0


Here are some selected columns from the data:
player - name of the player
pos - the position of the player
g - number of games the player was in
gs - number of games the player started
pts - total points the player scored
There are many more columns in the data, mostly containing information
about average player game performance over the course of the season.
See this site for an explanation of the rest of them.
We can read our dataset in and figure out which columns are present:

In [ ]:
                                 K NEAREST NEIGHBOURS

In [ ]:
working Principle Of KNN

    The kNN algorithm is belongs to the family of instance-based, competitive learning and lazy learning algorithms.

Instance-based algorithms are those algorithms that model the problem using data instances (or rows) in order to make predictive decisions. The kNN algorithm is an extreme form of instance-based methods because all training observations are retained as part of the model.
 
    It is a competitive learning algorithm, because it internally uses competition between model elements (data instances) in order to make a predictive decision. The objective similarity measure between data instances causes each data instance to compete to “win” or be most similar to a given unseen data instance and contribute to a prediction.

Lazy learning refers to the fact that the algorithm does not build a model until the time that a prediction is required. It is lazy because it only does work at the last second. This has the benefit of only including data relevant to the unseen data, called a localized model. A disadvantage is that it can be computationally expensive to repeat the same or similar searches over larger training datasets.
 
kNN is powerful because it does not assume anything about the data, other than a distance measure can be calculated consistently between any two instances. As such, it is called non-parametric or non-linear as it does not assume a functional form.

Uses Euclidean distance to measure the distance between the points

Euclidean distance is the most commonly used distance measure.
Euclidean distance also called as simply distance. 
The usage of Euclidean distance measure is highly recommended when data is dense or continuous. 
Euclidean distance is the best proximity measure. 
The Euclidean distance between two points is the length of the path connecting them.
The Pythagorean theorem gives this distance between two points.

In [4]:
import pandas as pd
nba=pd.read_csv(r"C:\Users\Chidi\Downloads\nba_2013.csv")
nba.head(10)

,player,pos,age,bref_team_id,g,gs,mp,fg,fga,fg.,...,drb,trb,ast,stl,blk,tov,pf,pts,season,season_end
0,Quincy Acy,SF,23,TOT,63,0,847,66,141,0.468,...,144,216,28,23,26,30,122,171,2013-2014,2013
1,Steven Adams,C,20,OKC,81,20,1197,93,185,0.503,...,190,332,43,40,57,71,203,265,2013-2014,2013
2,Jeff Adrien,PF,27,TOT,53,12,961,143,275,0.520,...,204,306,38,24,36,39,108,362,2013-2014,2013
3,Arron Afflalo,SG,28,ORL,73,73,2552,464,1011,0.459,...,230,262,248,35,3,146,136,1330,2013-2014,2013
4,Alexis Ajinca,C,25,NOP,56,30,951,136,249,0.546,...,183,277,40,23,46,63,187,328,2013-2014,2013
5,Cole Aldrich,C,25,NYK,46,2,330,33,61,0.541,...,92,129,14,8,30,18,40,92,2013-2014,2013
6,LaMarcus Aldridge,PF,28,POR,69,69,2498,652,1423,0.458,...,599,765,178,63,68,123,147,1603,2013-2014,2013
7,Lavoy Allen,PF,24,TOT,65,2,1072,134,300,0.447,...,192,311,71,24,33,44,126,303,2013-2014,2013
8,Ray Allen,SG,38,MIA,73,9,1936,240,543,0.442,...,182,205,143,54,8,84,115,701,2013-2014,2013
9,Tony Allen,SG,32,MEM,55,28,1278,204,413,0.494,...,129,208,94,90,19,90,121,495,2013-2014,2013

In [17]:

nba.columns

Index(['player', 'pos', 'age', 'bref_team_id', 'g', 'gs', 'mp', 'fg', 'fga',
       'fg.', 'x3p', 'x3pa', 'x3p.', 'x2p', 'x2pa', 'x2p.', 'efg.', 'ft',
       'fta', 'ft.', 'orb', 'drb', 'trb', 'ast', 'stl', 'blk', 'tov', 'pf',
       'pts', 'season', 'season_end'],
      dtype='object')

In [63]:
# The columns that we will be making predictions with.
xcolumn = [ 'G', 'GS', 'MP', 'FG', 'FGA', 'FG.', 'x3P', 'x3PA',
 'x3P.', 'x2P', 'x2PA', 'x2P.', 'eFG.', 'FT', 'FTA', 'FT.', 'ORB', 'DRB', 'TRB', 'AST',
 'STL', 'BLK', 'TOV', 'PF']

In [180]:
#Selecting coloumns 
xcolumn=nba.iloc[: , 4:28]
xcolumn.head(10)

,g,gs,mp,fg,fga,fg.,x3p,x3pa,x3p.,x2p,...,fta,ft.,orb,drb,trb,ast,stl,blk,tov,pf
0,63,0,847,66,141,0.468,4,15,0.266667,62,...,53,0.660,72,144,216,28,23,26,30,122
1,81,20,1197,93,185,0.503,0,0,NaN,93,...,136,0.581,142,190,332,43,40,57,71,203
2,53,12,961,143,275,0.520,0,0,NaN,143,...,119,0.639,102,204,306,38,24,36,39,108
3,73,73,2552,464,1011,0.459,128,300,0.426667,336,...,336,0.815,32,230,262,248,35,3,146,136
4,56,30,951,136,249,0.546,0,1,0.000000,136,...,67,0.836,94,183,277,40,23,46,63,187
5,46,2,330,33,61,0.541,0,0,NaN,33,...,30,0.867,37,92,129,14,8,30,18,40
6,69,69,2498,652,1423,0.458,3,15,0.200000,649,...,360,0.822,166,599,765,178,63,68,123,147
7,65,2,1072,134,300,0.447,2,13,0.153846,132,...,50,0.660,119,192,311,71,24,33,44,126
8,73,9,1936,240,543,0.442,116,309,0.375405,124,...,116,0.905,23,182,205,143,54,8,84,115
9,55,28,1278,204,413,0.494,11,47,0.234043,193,...,121,0.628,79,129,208,94,90,19,90,121

In [181]:
import numpy as np
from sklearn.preprocessing import Imputer
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsRegressor
from sklearn.metrics import accuracy_score

In [108]:
#For treating the NAN and the Null values, Imputer, is used  to replace the NAN values with the median
imp = Imputer(missing_values="NaN", strategy='median', axis=0)

xcolumn = imp.fit_transform(xcolumn)
xcolumn.shape

C:\Users\Chidi\Anaconda3\lib\site-packages\sklearn\utils\deprecation.py:58: DeprecationWarning: Class Imputer is deprecated; Imputer was deprecated in version 0.20 and will be removed in 0.22. Import impute.SimpleImputer from sklearn instead.
  warnings.warn(msg, category=DeprecationWarning)

(481, 24)

In [112]:

# The column that we want to predict.
ycolumn = nba.iloc[: ,28]
ycolumn=np.array(ycolumn)
ycolumn.shape

(481,)

In [104]:
# Create the knn model assuming the number of neighbours as 5
knn = KNeighborsRegressor(n_neighbors=5)

In [113]:
#Splitting the dataset as training and testing sets,allocating 30 percentage of data  for testing and the rest for training
x_train, x_test, y_train, y_test = train_test_split(
 xcolumn, ycolumn, test_size = 0.3, random_state = 100)

In [114]:
# Fit the model on the training data.
knn.fit(x_train,y_train)

KNeighborsRegressor(algorithm='auto', leaf_size=30, metric='minkowski',
          metric_params=None, n_jobs=None, n_neighbors=5, p=2,
          weights='uniform')

In [177]:
# Make predictions on the test set using the fit model.
ypredict= knn.predict(x_test)
ypredict

array([5.6100e+02, 4.5680e+02, 1.8480e+02, 1.4280e+02, 2.3200e+01,
       1.7140e+02, 8.9200e+01, 7.8800e+01, 9.6000e+00, 3.0600e+01,
       6.1000e+01, 1.3180e+02, 8.2000e+01, 1.5800e+01, 4.1360e+02,
       1.1410e+03, 3.2120e+02, 6.5180e+02, 4.6040e+02, 6.8500e+02,
       5.4000e+01, 1.3246e+03, 1.1276e+03, 8.3660e+02, 8.0000e-01,
       5.4420e+02, 1.0460e+03, 6.0000e-01, 2.8840e+02, 2.0100e+02,
       8.0900e+02, 3.2940e+02, 4.0880e+02, 1.0172e+03, 2.3500e+02,
       3.5600e+02, 7.8180e+02, 2.9800e+01, 1.2180e+02, 7.2360e+02,
       5.6900e+02, 2.0160e+02, 5.8360e+02, 2.0480e+02, 3.7600e+01,
       4.4480e+02, 8.8000e+01, 1.0498e+03, 1.0800e+01, 5.0240e+02,
       1.1152e+03, 1.7068e+03, 9.6700e+02, 6.8580e+02, 6.5940e+02,
       1.7980e+03, 7.6480e+02, 1.4000e+00, 5.6900e+02, 9.0020e+02,
       5.9260e+02, 1.1640e+02, 5.8800e+02, 1.0498e+03, 2.7000e+02,
       9.9800e+02, 1.1156e+03, 1.0420e+03, 1.1000e+03, 4.5260e+02,
       3.7000e+01, 1.0296e+03, 3.6940e+02, 4.3200e+01, 1.6740e+02,
       1.3016e+03, 4.5680e+02, 7.1960e+02, 3.2000e+00, 4.2000e+00,
       2.7800e+02, 1.0140e+02, 1.9840e+02, 1.0180e+02, 7.5400e+02,
       5.4920e+02, 5.3500e+02, 4.7680e+02, 2.2300e+02, 3.7600e+01,
       8.7440e+02, 1.8520e+02, 1.2564e+03, 3.4920e+02, 1.2722e+03,
       3.3860e+02, 1.7780e+02, 1.9864e+03, 8.3780e+02, 8.6000e+00,
       4.2420e+02, 3.5020e+02, 4.4220e+02, 1.3986e+03, 3.2060e+02,
       5.0800e+02, 7.9040e+02, 1.9120e+02, 1.2294e+03, 1.4540e+02,
       1.5808e+03, 1.5400e+01, 7.9320e+02, 5.8880e+02, 3.5020e+02,
       3.1800e+01, 5.4240e+02, 7.7660e+02, 1.2000e+00, 2.8320e+02,
       3.4920e+02, 6.4220e+02, 3.9260e+02, 2.1200e+01, 1.3556e+03,
       3.3600e+02, 6.9680e+02, 1.1240e+03, 5.7540e+02, 6.6360e+02,
       1.1156e+03, 1.6160e+02, 3.9500e+02, 2.0680e+02, 1.0980e+02,
       3.2800e+01, 9.3280e+02, 7.9340e+02, 3.3100e+02, 5.5980e+02,
       1.0136e+03, 1.6000e+00, 2.8640e+02, 7.0680e+02, 8.2000e+01])

In [183]:
#Since Regressor returns the exact value this is the score fetched by the nba_Players for the given year
result=knn.score(x_test,y_test)
np.round(result,3)

0.969